# Generated by Django 3.1.4 on 2021-03-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=320)),
                ('email_id', models.CharField(max_length=320)),
                ('phone_number', models.CharField(max_length=15)),
                ('query', models.TextField()),
                ('received_on', models.DateTimeField()),
                ('service_provided_by', models.CharField(max_length=12)),
                ('reply', models.TextField()),
                ('replied_on', models.DateTimeField(null=True)),
                ('satisfaction', models.CharField(max_length=15)),
                ('review_mail', models.CharField(default='pending', max_length=10)),
            ],
            options={
                'db_table': 'customer_enquiry',
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_provider_id', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=320)),
                ('email_id', models.CharField(max_length=320)),
                ('added_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'service_provider',
            },
        ),
    ]
